# Generated by Django 4.0 on 2021-12-08 11:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=256)),
                ('startDate', models.DateField(default=datetime.datetime.today)),
                ('endDate', models.DateField(default=datetime.datetime.today)),
                ('status', models.CharField(choices=[('Done', 'Done'), ('On Going', 'Ongoing'), ('Exceeded', 'Exceeded')], default='On Going', max_length=10)),
            ],
            options={
                'db_table': 'tasks',
                'ordering': ['-status', 'endDate'],
            },
        ),
    ]
